#!/bin/sh

#set -eo pipefail

action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME
param=${CNAB_P_HELLO:-hello}

echo "$param world"
case $action in
    install)
    "${GOPATH}/terraform" apply -auto-approve
    ;;
    uninstall)
    "${GOPATH}/terraform" destroy -auto-approve
    ;;
    status)
    "${GOPATH}/terraform" plan
    ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"