# The Vagrantfile is expected to be run like:
# vagrant up --provider hyperv

$script = <<-'SCRIPT'
apt-get install -y unzip wget git
cd /tmp
git clone https://github.com/OctopusDeploy/OctopusGuides.git
cd OctopusGuides
git checkout working2
chmod 777 -R /tmp/OctopusGuides
cd /tmp/OctopusGuides/vm
./java-jenkins-websphere.sh > /tmp/cucumber.logs
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "octopusdeploy/guide-common-base"
  config.vm.network 'public_network', bridge: 'Default Switch'
  config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.provider "hyperv" do |v|
        v.vmname = "Jenkins, Websphere and Octopus"
        v.memory = 6144
        v.cpus = 4

    end
    config.vm.provider "virtualbox" do |v|
        v.name = "Jenkins, Websphere and Octopus"
        v.memory = 6144
        v.cpus = 4
        v.customize ["modifyvm", :id, "--vram", "128"]
        v.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
        v.customize ["storagectl", :id, "--name", "SATA Controller", "--hostiocache", "on"]
    end
  config.vm.provision "shell", inline: $script, env: {
      "SLACK_HOOK_URL" => ENV["SLACK_HOOK_URL"],
      "AWS_ACCESS_KEY_ID" => ENV["AWS_ACCESS_KEY_ID"],
      "AWS_SECRET_ACCESS_KEY" => ENV["AWS_SECRET_ACCESS_KEY"],
      "AWS_DEFAULT_REGION" => "us-east-1"}
end
