# The Vagrantfile is expected to be run like:
# vagrant up --provider hyperv

$script = <<-'SCRIPT'
# Add the google DNS provider
sed -i 's/#DNS=/DNS=8.8.8.8/g' /etc/systemd/resolved.conf
sudo systemctl restart systemd-resolved

apt-get install -y unzip wget git
cd /tmp
git clone https://github.com/OctopusDeploy/OctopusGuides.git
chmod 777 -R OctopusGuides
cd OctopusGuides/vm
git checkout origin/ubuntufocal
./common-base.sh  > /tmp/cucumber.logs
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_version = "202005.21.0"
  config.vm.network 'public_network', bridge: 'Default Switch'
  config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.provider "hyperv" do |v|
        v.vmname = "Common guides base"
        v.memory = 4096
        v.cpus = 4

    end
    config.vm.provider "virtualbox" do |v|
        v.name = "Common guides base"
        v.memory = 4096
        v.cpus = 4
        v.customize ["modifyvm", :id, "--vram", "128"]
        v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
        v.customize ["storagectl", :id, "--name", "SATA Controller", "--hostiocache", "on"]
    end
  config.vm.provision "shell", inline: $script, env: {
      "SLACK_HOOK_URL" => ENV["SLACK_HOOK_URL"],
      "AWS_ACCESS_KEY_ID" => ENV["AWS_ACCESS_KEY_ID"],
      "AWS_SECRET_ACCESS_KEY" => ENV["AWS_SECRET_ACCESS_KEY"],
      "AWS_DEFAULT_REGION" => "us-east-1"}
end
