name: ASP.NET Azure DevOps Artifactory Feed Azure Website Video
on:
#  push:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1,16 * *'
jobs:
  build:
    if: >-
      (github.event_name != 'repository_dispatch') ||
      (github.event.client_payload.workflow == github.workflow) ||
      (github.event.client_payload.workflow == 'all') ||
      (github.event.client_payload.workflow == 'azuredevops-aspnet-video')
    env:
      AZURE_URL: http://localhost:9090/
      BUILD_NAME: "aspnet-app-git-azure-devops-artifactory-azurewebapp"
      SMTP_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ARTIFACTORY_KEY: ${{ secrets.ARTIFACTORY_KEY }}
      SLACK_HOOK_URL: ${{ secrets.SLACK_PRIVATE_HOOK_URL_1 }}
      WISTIA_USERNAME: ${{ secrets.WISTIA_USERNAME }}
      WISTIA_PASSWORD: ${{ secrets.WISTIA_PASSWORD }}
      EXTERNAL_APPLICATION_PASSWORD: ${{ secrets.ExternalApplicationPassword }}
      EXTERNAL_APPLICATION_TENANT_ID: ${{ secrets.ExternalApplicationTenantID }}
      EXTERNAL_AZURE_TENANT_ID: ${{ secrets.ExternalAzureTenantID }}
      EXTERNAL_AZURE_SUBSCRIPTION_ID: ${{ secrets.ExternalAzureSubscriptionID }}
      DEV_RES_GROUP: azuredevopsaspnetartifactoryfeedviddev
      TEST_RES_GROUP: azuredeopsaspnetartifactoryfeedvidtest
      PROD_RES_GROUP: azuredevopsaspnetartifactoryfeedvidprod
      MEDIA_PATH: C:\screenshots
      CUCUMBER_TAGS: >-
        (not @browserspecific or @firefox) and
        (not @destinationspecific or @azure-web-app) and
        (not @repositoryspecific or @artifactory) and
        (not @applicationspecific or @aspnet) and
        (not @sourcespecific or @git)
      WISTIA_MEDIA_ID: l4x3nd27e2
      DISABLE_HIGHLIGHTS: true
      DISABLE_SCREENSHOTS: true
      MOVE_TO_MOUSE_CUSROR: true
      MOUSE_VERTICAL_OFFSET: 74
      SCREENSHOT_BUCKET: octopus-guides-screenshots
      STHREE_SCREENSHOT_ENABLED: true
      GIT_URL: https://github.com/OctopusSamples/RandomQuotes-aspmvc4.git
      NUGET_PATH: 'RandomQuotes\obj\octopacked\'
      VIDEO_FILE_NAME: aspnet-azuredevops-artifactory-feed-azure.mp4
      SCREENSHOT_PATH:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2


    - name: Set screen resolution
      shell: powershell
      run: ./scripts/windows/set-lowresolution.ps1

    - name: Disable Windows Defender
      shell: powershell
      run: reg add 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection' /v DisableRealtimeMonitoring /t REG_DWORD /d 1

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Execute puppet
      shell: powershell
      run: ./install.ps1 -Scripts azurecli.pp

    - name: Create Web App
      shell: powershell
      run: |
        ./create-azure-web-app "$env:DEV_RES_GROUP"
        ./create-azure-web-app "$env:TEST_RES_GROUP"
        ./create-azure-web-app "$env:PROD_RES_GROUP"

    - name: Free some space
      shell: powershell
      run: ./scripts/windows/free-space.ps1

    - name: Execute puppet
      shell: powershell
      run: ./install.ps1 -Scripts sqlserverexpress.pp,azuredevops.pp,artifactory.pp,utilities.pp,dotnetutilities.pp,octopus.pp,iis.pp,sleep.pp,azurewait.pp,azuredevopsagent.pp

    - name: Configure Artifactory
      shell: powershell
      run: ./scripts/windows/configure-artifactory.ps1

    - name: Create API key
      shell: powershell
      run: ./scripts/windows/create-apikey.ps1

    - name: Create API key for tests
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\windows\octopus-api-key.pp --disable_warnings=deprecations'

    - name: Create Azure Devops Project
      shell: powershell
      run: ./scripts/windows/azuredevops-create-project.ps1

    - name: Create the Octopus External Feed
      shell: powershell
      run: ./scripts/windows/create-externalfeed.ps1

    - name: Create the Octopus Environments
      shell: powershell
      run: ./scripts/windows/create-environments.ps1

    - name: Create the Octopus Azure Account
      shell: powershell
      run: ./scripts/windows/create-azureaccount.ps1

    - name: Create Dev Azure target
      shell: powershell
      run: ./scripts/windows/create-devazuretarget.ps1

    - name: Create Test Azure target
      shell: powershell
      run: ./scripts/windows/create-testazuretarget.ps1

    - name: Create Prod Azure target
      shell: powershell
      run: ./scripts/windows/create-prodazuretarget.ps1

    - name: Create Octopus Project
      shell: powershell
      run: ./scripts/windows/create-octopusaspnetproject.ps1

    - name: Open Random Quotes
      shell: powershell
      run: ./scripts/windows/open-devazurewebapp.ps1

    - name: Add a deployment step
      shell: powershell
      run: ./scripts/windows/azuredevops-create-deployment.ps1

    - name: Shutdown Azure Devops
      shell: powershell
      run: ./scripts/windows/stop-azuredevops.ps1

    - name: Add a lifecycle
      shell: powershell
      run: ./scripts/windows/create-lifecycle.ps1

    - name: Open Random Quotes
      shell: powershell
      run: ./scripts/windows/open-testazurewebapp.ps1

    - name: Add manual intervention
      shell: powershell
      run: ./scripts/windows/add-manualintervention.ps1

    - name: Add email notification
      shell: powershell
      run: ./scripts/windows/add-notification.ps1

    - name: Add users and team
      shell: powershell
      run: ./scripts/windows/create-usersandteams.ps1

    - name: View internal deployer dashboard
      shell: powershell
      run: ./scripts/windows/view-internaldeployerdashboard.ps1

    - name: View production deployer dashboard
      shell: powershell
      run: ./scripts/windows/view-productiondeployerdashboard.ps1

    - name: View audit logs
      shell: powershell
      run: ./scripts/windows/view-auditlogs.ps1

    - name: Process video
      if: always()
      shell: powershell
      run: ./scripts/windows/process-video.ps1

    - name: Upload video
      if: always()
      shell: powershell
      run: ./scripts/windows/upload-video.ps1

    - name: Replace Wistia Video
      shell: powershell
      run: ./scripts/windows/replace-wistia-video.ps1

    - name: Create badge
      shell: powershell
      run: ./scripts/windows/create-badge.ps1

    - name: Get agent logs
      if: always()
      shell: powershell
      run: ./install.ps1 -Scripts azuredevopsagentlogs.pp

    - name: Delete resource groups
      if: always()
      shell: powershell
      run: |
        ./delete-resource-group.ps1 "$env:DEV_RES_GROUP"
        ./delete-resource-group.ps1 "$env:TEST_RES_GROUP"
        ./delete-resource-group.ps1 "$env:PROD_RES_GROUP"
